export const HANDLE_ADD_USER = "HANDLE_ADD_USER"
export const HANDLE_DELETE_USER = "HANDLE_DELETE_USER"
export const HANDLE_EDIT_USER = "HANDLE_EDIT_USER"
export const HANDLE_SEARCH_USER = " HANDLE_SEARCH_USER"