export const GET_LIST_USER = "GET_LIST_USER";
export const GET_LIST_USER_SUCCESS = "GET_LIST_USER_SUCCESS";
export const GET_LIST_USER_DETAIL = "GET_LIST_USER_DETAIL";

export const GET_ADD_USER = "GET_ADD_USER";
export const GET_ADD_USER_SUCCESS = "GET_ADD_USER_SUCCESS"
export const GET_ADD_USER_DETAIL = "GET_ADD_USER_DETAIL"

export const GET_DELETE_USER = "GET_DELETE_USER";
export const GET_DELETE_USER_SUCCESS = "GET_DELETE_USER_SUCCESS";
export const GET_DELETE_USER_DETAIL = "GET_DELETE_USER_DETAIL";

export const GET_EDIT_USER = "GET_EDIT_USER"
export const GET_EDIT_USER_SUCCESS = "GET_EDIT_USER_SUCCESS"
export const GET_EDIT_USER_DETAIL = "GET_EDIT_USER_DETAIL"


