export const HANDLE_INCREMENT = "HANDLE_INCREMENT";
export const HANDLE_DECREMENT = "HANDLE_DECREMENT";
export const HANDLE_INCREMENT_WITH_PAYLOAD = "HANDLE_INCREMENT_WITH_PAYLOAD";
export const HANDLE_DECREMENT_WITH_PAYLOAD = "HANDLE_DECREMENT_WITH_PAYLOAD";
export const HANDLE_ONMUNTIPLY_WITH_PAYLOAD = "HANDLE_ONMUNTIPLY_WITH_PAYLOAD"